CREATE TABLE `banner_reservations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`owner_email` text NOT NULL,
	`business_name` text NOT NULL,
	`business_type` text NOT NULL,
	`campaign_title` text NOT NULL,
	`destination_url` text DEFAULT '' NOT NULL,
	`cities_json` text NOT NULL,
	`start_date` text NOT NULL,
	`end_date` text NOT NULL,
	`reserved_days` integer NOT NULL,
	`city_count` integer NOT NULL,
	`city_day_rate` integer NOT NULL,
	`total_price` integer NOT NULL,
	`payment_status` text DEFAULT 'demo_paid' NOT NULL,
	`review_status` text DEFAULT 'pending' NOT NULL,
	`admin_note` text DEFAULT '' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
