import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const storyPromotions = sqliteTable("story_promotions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerKey: text("owner_key").notNull(),
  listingId: integer("listing_id").notNull(),
  title: text("title").notNull(),
  brand: text("brand").notNull().default(""),
  model: text("model").notNull().default(""),
  year: text("year").notNull().default(""),
  priceToman: integer("price_toman").notNull().default(0),
  province: text("province").notNull().default(""),
  city: text("city").notNull().default(""),
  neighborhood: text("neighborhood").notNull().default(""),
  listingOwnerType: text("listing_owner_type").notNull().default("personal"),
  sellerDisplayName: text("seller_display_name").notNull().default(""),
  dealerId: integer("dealer_id"),
  coverImageUrl: text("cover_image_url").notNull().default(""),
  publicUrl: text("public_url").notNull(),
  couponCode: text("coupon_code").notNull().default(""),
  originalAmountToman: integer("original_amount_toman").notNull().default(0),
  discountAmountToman: integer("discount_amount_toman").notNull().default(0),
  finalAmountToman: integer("final_amount_toman").notNull().default(0),
  status: text("status").notNull().default("active"),
  startsAt: text("starts_at").notNull(),
  expiresAt: text("expires_at").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
