"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Item = { id: number; score: number; province: string; reason: string; listing: { id: number; title: string; brand: string; model: string; year: number; priceToman: number; coverUrl?: string; publicUrl: string } };
export default function MarketFloorPage() {
  const [items, setItems] = useState<Item[]>([]);
  useEffect(() => { fetch("/api/market-floor/public", { cache: "no-store" }).then((r) => r.json()).then((d) => setItems(d.success ? d.data : [])).catch(() => setItems([])); }, []);
  return <main dir="rtl" style={{ width: "min(1180px,calc(100% - 24px))", margin: "28px auto 90px" }}><header style={{ padding: "38px clamp(20px,6vw,64px)", borderRadius: 30, color: "white", background: "radial-gradient(circle at 10% 0,#fbbf2455,transparent 30%),linear-gradient(135deg,#21102f,#6d28d9)" }}><small>انتخاب هوشمند چاکود</small><h1 style={{ fontSize: "clamp(34px,7vw,64px)", margin: "8px 0" }}>کف بازار</h1><p>حداکثر ۱۰ فرصت واقعی از هر استان؛ بدون پر کردن اجباری ظرفیت.</p><Link href="/account/market-floor" style={{ display: "inline-flex", marginTop: 12, padding: "12px 18px", borderRadius: 13, color: "#4c1d95", background: "#fff" }}>آگهی من هم بررسی شود</Link></header>
  <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: 14, marginTop: 22 }}>{items.length ? items.map((item) => <Link href={item.listing.publicUrl} key={item.id} style={{ overflow: "hidden", border: "1px solid #e7deed", borderRadius: 22, color: "#24152d", background: "#fff", textDecoration: "none", boxShadow: "0 14px 34px #25143112" }}>{item.listing.coverUrl ? <img src={item.listing.coverUrl} alt="" style={{ width: "100%", height: 175, objectFit: "cover" }} /> : <div style={{ height: 175, display: "grid", placeItems: "center", color: "#fff", background: "linear-gradient(135deg,#30164b,#7c3aed)" }}>چاکود</div>}<div style={{ padding: 16 }}><span style={{ padding: "5px 8px", borderRadius: 999, color: "#047857", background: "#d1fae5", fontSize: 11 }}>امتیاز فرصت {item.score}</span><h2 style={{ fontSize: 17 }}>{item.listing.title}</h2><p style={{ color: "#75677f", fontSize: 12 }}>{item.province} · {item.reason}</p></div></Link>) : <div style={{ padding: 30, border: "1px dashed #d8cae3", borderRadius: 20, textAlign: "center" }}><strong>هنوز فرصت تأییدشده‌ای در چرخه فعلی نیست</strong><p>ظرفیت با آگهی ضعیف پر نمی‌شود.</p></div>}</section></main>;
}
